setwd("/Users/ismael/Proyectos/BIOLAB1")
library(Biostrings)
dnaSeq = DNAString("TTCAGATCTAGTTCGTGTGTGACTGATGATCTGTCACACGTTTTTCTGATCTTCTGACTAGTCGAT")
dnaSeq[1:10]
substr(dnaSeq,1,10)
length(dnaSeq)
reverseComplement(dnaSeq)
alphabetFrequency(dnaSeq)
compareStrings(dnaSeq,dnaSeq)
dnaSeq2 = DNAString("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA") 
compareStrings(dnaSeq,dnaSeq2)
dnaSeq3 = readDNAStringSet("Rattus_chromosome1.fa")
length(dnaSeq3)
reverseComplement(dnaSeq3)
alphabetFrequency(dnaSeq3)
dinucleotideFrequency(dnaSeq3)